basePath: /
host: localhost:3000
info:
  contact: {}
  description: This is the API for the Back Platform Medical Catalog
  title: Back Platform API for Medical Catalog
  version: "1.0"
paths: {}
securityDefinitions:
  Bearer Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
